apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bjd4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bjd4
    app.kubernetes.io/part-of: tkwch-fix-0075-0005-app
  name: devfile-sample-bjd4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bjd4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bjd4
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0005-tenant/tkwch-fix-0075-0005-app/devfile-sample-bjd4@sha256:1c5d7d819a8846809dacd724b4ddd78645181019ecbdbdb25fd364559703c481
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
